In [2]:
%pip install pandas numpy scikit-learn matplotlib seaborn jupyter streamlit plotly holidays -q

Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
import streamlit as st
import holidays

In [12]:
# Cargar datos de entrenamiento
df_ventas = pd.read_csv('../data/raw/entrenamiento/ventas.csv')
df_competencia = pd.read_csv('../data/raw/entrenamiento/competencia.csv')

# Convertir fecha a datetime en ambos dataframes
df_ventas['fecha'] = pd.to_datetime(df_ventas['fecha'], errors='coerce')
df_competencia['fecha'] = pd.to_datetime(df_competencia['fecha'], errors='coerce')

#verificar la conversión de las fechas
print("tipo de fechas en df_ventas:", df_ventas['fecha'].dtype)
print("tipo de fechas en df_competencia:", df_competencia['fecha'].dtype)

tipo de fechas en df_ventas: datetime64[us]
tipo de fechas en df_competencia: datetime64[us]

In [7]:
print("ventas")
print(df_ventas.head())
print("competencia")
print(df_competencia.head())

ventas
        fecha producto_id                            nombre categoria  \
0  2021-10-25    PROD_001          Nike Air Zoom Pegasus 40   Running
1  2021-10-25    PROD_002              Adidas Ultraboost 23   Running
2  2021-10-25    PROD_003               Asics Gel Nimbus 25   Running
3  2021-10-25    PROD_004  New Balance Fresh Foam X 1080v12   Running
4  2021-10-25    PROD_005                Nike Dri-FIT Miler   Running

         subcategoria  precio_base  es_estrella  unidades_vendidas  \
0  Zapatillas Running          115         True                  6
1  Zapatillas Running          135         True                 10
2  Zapatillas Running           85        False                  2
3  Zapatillas Running           75        False                  2
4        Ropa Running           35        False                  2

   precio_venta  ingresos
0        118.36    710.16
1        136.82   1368.20
2         84.93    169.86
3         75.42    150.84
4         35.87     71.74
competencia
        fecha producto_id  Amazon  Decathlon  Deporvillage
0  2021-10-25    PROD_001   82.96     111.88         97.43
1  2021-10-25    PROD_002  112.56     108.61        115.58
2  2021-10-25    PROD_003   79.79      78.44         80.11
3  2021-10-25    PROD_004   72.60      67.29         74.45
4  2021-10-25    PROD_005   37.71      33.60         33.07

In [8]:
df_ventas.head(10)

,fecha,producto_id,nombre,categoria,subcategoria,precio_base,es_estrella,unidades_vendidas,precio_venta,ingresos
0,2021-10-25,PROD_001,Nike Air Zoom Pegasus 40,Running,Zapatillas Running,115,True,6,118.36,710.16
1,2021-10-25,PROD_002,Adidas Ultraboost 23,Running,Zapatillas Running,135,True,10,136.82,1368.20
2,2021-10-25,PROD_003,Asics Gel Nimbus 25,Running,Zapatillas Running,85,False,2,84.93,169.86
3,2021-10-25,PROD_004,New Balance Fresh Foam X 1080v12,Running,Zapatillas Running,75,False,2,75.42,150.84
4,2021-10-25,PROD_005,Nike Dri-FIT Miler,Running,Ropa Running,35,False,2,35.87,71.74
5,2021-10-25,PROD_006,Adidas Own The Run Jacket,Running,Ropa Running,65,False,2,65.51,131.02
6,2021-10-25,PROD_007,Puma Velocity Nitro 2,Running,Zapatillas Running,70,False,2,70.98,141.96
7,2021-10-25,PROD_008,Reebok Floatride Energy 5,Running,Zapatillas Running,65,False,2,66.60,133.20
8,2021-10-25,PROD_009,Bowflex SelectTech 552,Fitness,Mancuernas Ajustables,400,True,2,392.31,784.62
9,2021-10-25,PROD_010,Domyos BM900,Fitness,Banco Gimnasio,175,True,2,174.92,349.84

In [7]:
df_competencia.columns

Index(['fecha', 'producto_id', 'Amazon', 'Decathlon', 'Deporvillage'], dtype='str')

In [6]:
df_ventas.columns

Index(['fecha', 'producto_id', 'nombre', 'categoria', 'subcategoria',
       'precio_base', 'es_estrella', 'unidades_vendidas', 'precio_venta',
       'ingresos'],
      dtype='str')

In [7]:
df_competencia.columns

Index(['fecha', 'producto_id', 'Amazon', 'Decathlon', 'Deporvillage'], dtype='str')

In [9]:
# Informe de calidad de datos para df_competencia
print('=== INFORME DE CALIDAD DE DATOS: df_competencia ===')
print(f"Forma del dataframe: {df_competencia.shape[0]} filas, {df_competencia.shape[1]} columnas")
print('\nTipos de variables:')
print(df_competencia.dtypes)
print('\nNulos por columna:')
print(df_competencia.isnull().sum())
print('\nPorcentaje de nulos por columna:')
print((df_competencia.isnull().mean() * 100).round(2))
print(f"\nFilas duplicadas: {df_competencia.duplicated().sum()}")
print('\nResumen descriptivo de variables numéricas:')
print(df_competencia.describe(include=[np.number]).T)
print('\nResumen descriptivo de variables no numéricas:')
print(df_competencia.describe(include=['object', 'category']).T)
print('\nValores únicos por columna:')
for col in df_competencia.columns:
    print(f"- {col}: {df_competencia[col].nunique()} únicos")# Informe de calidad de datos para df_ventas
print('=== INFORME DE CALIDAD DE DATOS: df_ventas ===')
print(f"Forma del dataframe: {df_ventas.shape[0]} filas, {df_ventas.shape[1]} columnas")
print('\nTipos de variables:')
print(df_ventas.dtypes)
print('\nNulos por columna:')
print(df_ventas.isnull().sum())
print('\nPorcentaje de nulos por columna:')
print((df_ventas.isnull().mean() * 100).round(2))
print(f"\nFilas duplicadas: {df_ventas.duplicated().sum()}")
print('\nResumen descriptivo de variables numéricas:')
print(df_ventas.describe(include=[np.number]).T)
print('\nResumen descriptivo de variables no numéricas:')
print(df_ventas.describe(include=['object', 'category']).T)
print('\nValores únicos por columna:')
for col in df_ventas.columns:
    print(f"- {col}: {df_ventas[col].nunique()} únicos")

=== INFORME DE CALIDAD DE DATOS: df_competencia ===
Forma del dataframe: 3552 filas, 5 columnas

Tipos de variables:
fecha               str
producto_id         str
Amazon          float64
Decathlon       float64
Deporvillage    float64
dtype: object

Nulos por columna:
fecha           0
producto_id     0
Amazon          0
Decathlon       0
Deporvillage    0
dtype: int64

Porcentaje de nulos por columna:
fecha           0.0
producto_id     0.0
Amazon          0.0
Decathlon       0.0
Deporvillage    0.0
dtype: float64

Filas duplicadas: 0

Resumen descriptivo de variables numéricas:
               count        mean         std    min      25%     50%  \
Amazon        3552.0  118.623407  156.095628  16.85  47.1175  73.180
Decathlon     3552.0  111.412182  148.508132  15.45  43.2850  66.285
Deporvillage  3552.0  118.894628  160.216448  16.77  47.3100  72.700

                   75%       max
Amazon        114.3425  858.3500
Decathlon     111.1725  867.3375
Deporvillage  114.9850  932.3250

Resumen descriptivo de variables no numéricas:
            count unique         top freq
fecha        3552    148  2021-10-25   24
producto_id  3552     24    PROD_001  148

Valores únicos por columna:
- fecha: 148 únicos
- producto_id: 24 únicos
- Amazon: 3125 únicos
- Decathlon: 3001 únicos
- Deporvillage: 3105 únicos
=== INFORME DE CALIDAD DE DATOS: df_ventas ===
Forma del dataframe: 3552 filas, 10 columnas

Tipos de variables:
fecha                    str
producto_id              str
nombre                   str
categoria                str
subcategoria             str
precio_base            int64
es_estrella             bool
unidades_vendidas      int64
precio_venta         float64
ingresos             float64
dtype: object

Nulos por columna:
fecha                0
producto_id          0
nombre               0
categoria            0
subcategoria         0
precio_base          0
es_estrella          0
unidades_vendidas    0
precio_venta         0
ingresos             0
dtype: int64

Porcentaje de nulos por columna:
fecha                0.0
producto_id          0.0
nombre               0.0
categoria            0.0
subcategoria         0.0
precio_base          0.0
es_estrella          0.0
unidades_vendidas    0.0
precio_venta         0.0
ingresos             0.0
dtype: float64

Filas duplicadas: 0

Resumen descriptivo de variables numéricas:
                    count        mean          std    min       25%     50%  \
precio_base        3552.0  123.125000   165.576753  20.00   48.7500   72.50
unidades_vendidas  3552.0    4.878660     6.311020   1.00    2.0000    3.00
precio_venta       3552.0  121.816546   164.017963  19.00   47.2125   71.81
ingresos           3552.0  605.972323  1079.071192  19.46  131.5350  216.57

                        75%       max
precio_base        118.7500    830.00
unidades_vendidas    5.0000     85.00
precio_venta       118.2200    854.22
ingresos           639.6375  14508.40

Resumen descriptivo de variables no numéricas:
             count unique                       top  freq
fecha         3552    148                2021-10-25    24
producto_id   3552     24                  PROD_001   148
nombre        3552     24  Nike Air Zoom Pegasus 40   148
categoria     3552      4                   Running  1184
subcategoria  3552     16        Zapatillas Running   888

Valores únicos por columna:
- fecha: 148 únicos
- producto_id: 24 únicos
- nombre: 24 únicos
- categoria: 4 únicos
- subcategoria: 16 únicos
- precio_base: 21 únicos
- es_estrella: 2 únicos
- unidades_vendidas: 52 únicos
- precio_venta: 2537 únicos
- ingresos: 3033 únicos

C:\Users\andre\AppData\Local\Temp\ipykernel_50368\3459239886.py:14: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df_competencia.describe(include=['object', 'category']).T)
C:\Users\andre\AppData\Local\Temp\ipykernel_50368\3459239886.py:30: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print(df_ventas.describe(include=['object', 'category']).T)

In [13]:
df_ventas.info()

<class 'pandas.DataFrame'>
RangeIndex: 3552 entries, 0 to 3551
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   fecha              3552 non-null   datetime64[us]
 1   producto_id        3552 non-null   str
 2   nombre             3552 non-null   str
 3   categoria          3552 non-null   str
 4   subcategoria       3552 non-null   str
 5   precio_base        3552 non-null   int64
 6   es_estrella        3552 non-null   bool
 7   unidades_vendidas  3552 non-null   int64
 8   precio_venta       3552 non-null   float64
 9   ingresos           3552 non-null   float64
dtypes: bool(1), datetime64[us](1), float64(2), int64(2), str(4)
memory usage: 433.1 KB

In [14]:
df_competencia.info()

<class 'pandas.DataFrame'>
RangeIndex: 3552 entries, 0 to 3551
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   fecha         3552 non-null   datetime64[us]
 1   producto_id   3552 non-null   str
 2   Amazon        3552 non-null   float64
 3   Decathlon     3552 non-null   float64
 4   Deporvillage  3552 non-null   float64
dtypes: datetime64[us](1), float64(3), str(1)
memory usage: 166.6 KB

In [15]:
# Integrar ventas y competencia en un único dataframe
# Claves: fecha y producto_id
df = df_ventas.merge(
    df_competencia,
    on=['fecha', 'producto_id'],
    how='inner'
)

print(df.head())
print('\nForma del dataframe unido:', df.shape)

       fecha producto_id                            nombre categoria  \
0 2021-10-25    PROD_001          Nike Air Zoom Pegasus 40   Running
1 2021-10-25    PROD_002              Adidas Ultraboost 23   Running
2 2021-10-25    PROD_003               Asics Gel Nimbus 25   Running
3 2021-10-25    PROD_004  New Balance Fresh Foam X 1080v12   Running
4 2021-10-25    PROD_005                Nike Dri-FIT Miler   Running

         subcategoria  precio_base  es_estrella  unidades_vendidas  \
0  Zapatillas Running          115         True                  6
1  Zapatillas Running          135         True                 10
2  Zapatillas Running           85        False                  2
3  Zapatillas Running           75        False                  2
4        Ropa Running           35        False                  2

   precio_venta  ingresos  Amazon  Decathlon  Deporvillage
0        118.36    710.16   82.96     111.88         97.43
1        136.82   1368.20  112.56     108.61        115.58
2         84.93    169.86   79.79      78.44         80.11
3         75.42    150.84   72.60      67.29         74.45
4         35.87     71.74   37.71      33.60         33.07

Forma del dataframe unido: (3552, 13)

In [16]:
df.head()

,fecha,producto_id,nombre,categoria,subcategoria,precio_base,es_estrella,unidades_vendidas,precio_venta,ingresos,Amazon,Decathlon,Deporvillage
0,2021-10-25,PROD_001,Nike Air Zoom Pegasus 40,Running,Zapatillas Running,115,True,6,118.36,710.16,82.96,111.88,97.43
1,2021-10-25,PROD_002,Adidas Ultraboost 23,Running,Zapatillas Running,135,True,10,136.82,1368.20,112.56,108.61,115.58
2,2021-10-25,PROD_003,Asics Gel Nimbus 25,Running,Zapatillas Running,85,False,2,84.93,169.86,79.79,78.44,80.11
3,2021-10-25,PROD_004,New Balance Fresh Foam X 1080v12,Running,Zapatillas Running,75,False,2,75.42,150.84,72.60,67.29,74.45
4,2021-10-25,PROD_005,Nike Dri-FIT Miler,Running,Ropa Running,35,False,2,35.87,71.74,37.71,33.60,33.07